name: CI

on: [push, pull_request]

jobs:
  test-env:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-latest]
    steps:
      - uses: actions/checkout@v3
      - uses: conda-incubator/setup-miniconda@v3
        with:
          python-version: 3.12
          environment-file: environment_mac.yml
          activate-environment: growbikenet
      - run: conda env update -n growbikenet -f environment_mac.yml
      - run: conda list
